<?php
$this->layout('../layouts/layout',[
    'title' => 'Xoluciones  | Marcas'
]);
?>

<?php $this->push('styles')?>
<!-- Estilos personalizados -->
<?php $this->end()?>

<?php $this->start('contents')?>
<!-- Contenido de la pagina -->
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <a is-modal="true" href="<?= URL . 'marca/detail' ?>" class="btn btn-primary btn-block">Nuevo</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10%">ID</th>
                        <th style="width: 30%">NOMBRE</th>
                        <th style="width: 40%">DESCRIPCION</th>
                        <th style="width: 20%"></th>
                    </tr>
                </thead>
                <Tbody>
                    <?php foreach($data as $row): ?>
                    <tr>
                        <td><?= $row->IdMarca ?></td>
                        <td><?= $row->Nombre ?></td>
                        <td><?= $row->Descripcion ?></td>
                        <td>
                            <a is-modal="true" href="<?= URL . "marca/detail/{$row->IdMarca}" ?>" class="btn btn-success btn-sm"><i class="fa fa-pencil"></i></a>
                            <a href="<?= URL . "marca/delete/{$row->IdMarca}" ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </Tbody>
            </table>
        </div>
    </div>
    <br>
</div>
<?php $this->stop()?>

<?php $this->start('myModal')?>
<?php
$title = 'Marca Detalle - Insertar';
$size = MUYGRANDE;
include MAINPATH . 'app/views/layouts/partials/_modalGenerico.phtml'
?>
<?php $this->stop()?>

<?php $this->push('scripts')?>
<script src="<?=URL.'js/scripts/modal_crud.js'?>"></script>
<script src="<?=URL.'js/scripts/delete_crud.js'?>"></script>
<?php $this->end()?>