<?php
$this->layout('../layouts/layout', [
    'title' => 'HTGVENTAS | TEST'
]);
?>

<?php $this->push('styles') ?>
<!-- Estilos personalizados -->
<?php $this->end() ?>

<?php $this->start('contents') ?>
<!-- Contenido de la pagina -->
<div class="container">
    <h1>Pagina de Prueba</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, assumenda saepe quo adipisci hic modi eum delectus similique aspernatur sequi expedita iure quas, dolor repellendus ullam facere, molestias sit rerum!</p>
</div>

<?php $this->stop() ?>

<?php $this->push('scripts') ?>
<!-- Scripts personalizados -->
<?php $this->end() ?>