<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Suma</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1>Suma</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <form action="<?= URL ?>test/suma" method="post">
                    <div class="form-group">
                        <label for="num1">Numero 1:</label>
                        <input type="number" name="num1" id="num1" class="form-control" value="<?= $num1 ?>">
                    </div>
                    <div class="form-group">
                        <label for="num2">Numero 2:</label>
                        <input type="number" name="num2" id="num2" class="form-control" value="<?= $num2 ?>">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Calcular</button>
                    </div>
                </form>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-8">
                Respuesta:
                <input type="text" class="form-control" value="<?= $rpta ?>" disabled>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>
</html>